services:
  dev:
    platform: "linux/amd64"
    image: cr.pointcaster.net/pointcaster-dev:latest-linux
    command: fish
    stdin_open: true
    tty: true
    working_dir: /pointcaster
    volumes: 
      - .:/pointcaster
  dev-win:
    platform: "windows/amd64"
    image: cr.pointcaster.net/pointcaster-dev:latest-windows
    command: powershell
    stdin_open: true
    tty: true
    working_dir: C:\pointcaster
    isolation: process
    # mem_limit: 14g
    # cpu_count: 22
    volumes: 
      - .:C:\pointcaster
      - pointcaster-windows-build-vol:C:\pointcaster\build
      - .\build\windows-release\install:C:\pointcaster\build\windows-release\install
      - .\build\pointreceiver-windows-release\install:C:\pointcaster\build\pointreceiver-windows-release\install
volumes:
  pointcaster-windows-build-vol: