#include <QQmlApplicationEngine>
#include "config_adapter.h"
#include "device_plugin_controller.h"
#include "device_status.h"
#include "settings_page_registry.h"
// #include "../qml/Pointcaster/Workspace/net_utils.h"

namespace pc::ui {

void register_qml_uncreatable_types() {

  // ui/models/config_adapter.h
  qmlRegisterUncreatableType<ConfigAdapter>(
      "Pointcaster", 1, 0, "ConfigAdapter",
      "ConfigAdapter is an abstract base for config structures that are "
      "generated by the precompile script at scripts/generate-qt-adapters.py");

  // ui/models/device_status.h
  qmlRegisterUncreatableMetaObject(pc::ui::staticMetaObject, "Pointcaster", 1,
                                   0, "UiEnums",
                                   "WorkspaceDeviceStatus is enum");

  // ui/models/device_plugin_controller.h
  qmlRegisterUncreatableType<pc::ui::DevicePluginController>(
      "Pointcaster", 1, 0, "DevicePluginController",
      "DevicePluginController is created in C++ only");

  // ui/models/settings_page_registry.h
  qmlRegisterSingletonInstance(
      "Pointcaster", 1, 0,
      "SettingsPageRegistry",
      SettingsPageRegistry::instance());

//   // ui/qml/Pointcaster/Workspace/net_utils.h
//   qmlRegisterSingletonType<pc::ui::qml::NetUtils>(
//       "Pointcaster.Workspace", 1, 0, "NetUtils",
//       [](QQmlEngine *, QJSEngine *) -> QObject * {
//         return new pc::ui::qml::NetUtils;
//       });
}

} // namespace pc::ui