#pragma once

#include "config_adapter.h"
#include "device_adapter.h"
#include "settings_page_registry.h"
#include "enum_adapters.h"

#include <ui/qml/color_picker.h>

#include <QQmlApplicationEngine>

namespace pc::ui {

inline void register_qml_uncreatable_types() {

  // ui/models/config_adapter.h
  qmlRegisterUncreatableType<ConfigAdapter>(
      "Pointcaster", 1, 0, "ConfigAdapter",
      "ConfigAdapter is an abstract base for config structures that are "
      "generated by scripts/generate-qt-adapters.py");

  // ui/models/device_adapter.h
  qmlRegisterUncreatableType<DeviceAdapter>(
      "Pointcaster", 1, 0, "DeviceAdapter",
      "DeviceAdapter is an abstract base for device adapters generated by "
      "scripts/generate-qt-adapters.py");

  // ui/models/enum_adapters.h (enum metaobject)
  qmlRegisterUncreatableMetaObject(
      pc::ui::staticMetaObject, "Pointcaster", 1, 0, "Enum",
      "Enum provides uncreatable enums (e.g. WorkspaceDeviceStatus, "
      "StreamChannelStatus)");

  // ui/models/settings_page_registry.h
  qmlRegisterSingletonInstance("Pointcaster", 1, 0, "SettingsPageRegistry",
                               SettingsPageRegistry::instance());

  //
  //   qmlRegisterType<pc::ui::qml::ColorPicker>("Pointcaster", 1, 0,
  //   "ColorPicker");

  // qmlRegisterSingletonType<pc::ui::qml::NetUtils>(...);
}

} // namespace pc::ui
