#pragma once

#include "config_adapter.h"
#include "device_adapter.h"
#include "device_status.h"
#include "settings_page_registry.h"

#include <QQmlApplicationEngine>

namespace pc::ui {

inline void register_qml_uncreatable_types() {

  // ui/models/config_adapter.h
  qmlRegisterUncreatableType<ConfigAdapter>(
      "Pointcaster", 1, 0, "ConfigAdapter",
      "ConfigAdapter is an abstract base for config structures that are "
      "generated by scripts/generate-qt-adapters.py");

  // ui/models/device_adapter.h
  qmlRegisterUncreatableType<DeviceAdapter>(
      "Pointcaster", 1, 0, "DeviceAdapter",
      "DeviceAdapter is an abstract base for device adapters generated by "
      "scripts/generate-qt-adapters.py");

  // ui/models/device_status.h (enum metaobject)
  qmlRegisterUncreatableMetaObject(
      pc::devices::ui::staticMetaObject, "Pointcaster", 1, 0, "UiEnums",
      "UiEnums provides uncreatable enums (e.g. WorkspaceDeviceStatus)");

  // ui/models/settings_page_registry.h
  qmlRegisterSingletonInstance("Pointcaster", 1, 0, "SettingsPageRegistry",
                               SettingsPageRegistry::instance());

  // qmlRegisterSingletonType<pc::ui::qml::NetUtils>(...);
}

} // namespace pc::ui
