# Windows release build, triggered by pushing a version tag e.g.:
#
#   git tag v0.2.2 && git push origin v0.2.2
#
# !! we are actually using straight up 'docker' commands here because
# our windows agent is a 'local' agent. I couldn't get this to
# work otherwise with windows containers...

when:
  - event: tag
  - event: manual

labels:
  platform: windows/amd64

variables:
  - &container_env
    POINTCASTER_DEV_IMAGE: cr.pointcaster.net/pointcaster-dev
    POINTCASTER_BUILD_VOLUME: pointcaster-ci-build
    DOCKER_HOST: npipe:////./pipe/dockerDesktopWindowsEngine

steps:
  - name: prepare
    image: pwsh
    environment: *container_env
    commands:
      - |
        docker pull $env:POINTCASTER_DEV_IMAGE
      - |
        docker volume rm --force $env:POINTCASTER_BUILD_VOLUME

  - name: configure
    image: pwsh
    environment: *container_env
    commands:
      - echo docker run -v ./:C:\pointcaster -v "$env:POINTCASTER_BUILD_VOLUME":"C:\pointcaster\build" $env:POINTCASTER_DEV_IMAGE cmake --preset windows-release
      - docker run -v ./:C:\pointcaster -v "$env:POINTCASTER_BUILD_VOLUME":"C:\pointcaster\build" $env:POINTCASTER_DEV_IMAGE cmake --preset windows-release

  - name: build
    image: pwsh
    environment: *container_env
    commands:
      - docker run -v ./:C:\pointcaster -v "$env:POINTCASTER_BUILD_VOLUME":"C:\pointcaster\build" $env:POINTCASTER_DEV_IMAGE cmake --build build/windows-release --target package

  - name: deploy
    image: pwsh
    environment: *container_env
    commands:
      - docker run -v ./:C:\pointcaster -v "$env:POINTCASTER_BUILD_VOLUME":"C:\pointcaster\build" $env:POINTCASTER_DEV_IMAGE cmake --build build/windows-release --target deploy
